ga_id: UA-XXXXXXXX-1

source: app
destination: public
baseurl: ""
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "bymagellan.co"
url: ""

compress_html:
  clippings: all
  comments: all

exclude:
  - _assets

keep_files:
  - assets

permalink: pretty

collections:
  projects:
    output: true
    permalink: /projects/:path/
